spring:
  datasource:
    url: jdbc:mysql://35.192.133.4:3310/rhino_blog?characterEncoding=utf-8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver